/**
 * OperationType
 * <p>
 * This enum provides a list of operations the server provides to the client.
 * </p>
 * 
 * @author Ropan Datta, L22
 * @version December 2, 2022
 */
public enum OperationType {
    IS_LOGGEDIN, LOGIN, LOGOUT, CREATE_USER, SET_DISPLAYIMAGE, GET_BLOCKED_USERS, BLOCK_USER, UNBLOCK_USER, GET_FOLLOWREQUESTS, SEND_FOLLOWREQUEST, CANCEL_FOLLOWREQUEST, ACCEPT_FOLLOWREQUEST, REJECT_FOLLOWREQUEST, CREATE_POST, FETCH_POST, UPVOTE_POST, DOWNVOTE_POST, FETCH_COMMENTS, CREATE_COMMENT, DELETE_COMMENT, SEARCH_USER, LOAD_FEED, TESTING
}
